### ISSUE TITLE
Update links to "UNIX for beginners"

### ISSUE THREAD

**Issue by olivertaylor** [brandon-rhodes/blog#2]
The "obscure Japanese web page" you mention [here](https://github.com/brandon-rhodes/blog/blame/master/texts/brandon/2012/one-sentence-per-line.rst#L121-L132) is down.

The PDF of UNIX for Beginners can be found [here](http://wolfram.schneider.org/bsd/7thEdManVol2/beginners/beginners.pdf), as can [the entire 7th edition manual](http://wolfram.schneider.org/bsd/7thEdManVol2/).

**Comment by brandon-rhodes** [comment]
Thanks for pointing out the broken link!

Alas, the PDF that you link to is the Second Edition dated 1997, and thus is not the edition that I describe in my blog post, that ‘describes a far more primitive version of the operating system than his more famous and more widely available “UNIX for Beginners — Second Edition” from 1978’.

I found that the original Japanese site got backed up by the Wayback Machine before it disappeared, so I have redirected the links there — let me know if they work for you, and thanks again for reporting the problem!
